total_scores = ['CDMEMORY', ' CDORIENT', 'CDJUDGE', 'CDCOMMUN', 'CDHOME', 'CDCARE',
'FAQTOTAL', 'CLOCKSCOR', 'COPYSCOR', 'TRAASCOR', 'TRABSCOR', 'DIGITSCOR', 'BNTTOTAL',
'AVDELTOT', 'AVDELERR2', 'MMSCORE', 'TOTSCORE', 'Q1SCORE', 'Q2SCORE', 'Q3SCORE', 'Q4SCORE', 'Q5SCORE',
'Q6SCORE', 'Q7SCORE', 'Q8SCORE', 'Q9SCORE', 'Q10SCORE', 'Q11SCORE', 'Q12SCORE', 'Q13SCORE', 'TOTAL13']

demographics = ['PTSOURCE', 'PTGENDER', 'PTDOBMM', 'PTDOBYY', 'PTHAND', 'PTMARRY', 'PTEDUCAT', 'PTWORK', 'PTNOTRT',
'PTRTYR', 'PTHOME', 'PTOTHOME', 'PTTLANG', 'PTPLANG', 'PTPSPEC', 'PTCOGBEG', 'PTMCIBEG', 'PTADBEG', 'PTADDX', 'PTETHCAT', 'PTRACCAT']

memory_test = ['MEMORY1', 'MEMORY2', 'MEMORY3', 'MEMORY4', 'MEMORY4', 'MEMORY5', 'MEMORY5', 'MEMORY6', 'MEMORY7', 'MEMORY7', 'MEMORY8', 'MEMORY8']

language_test = ['LANG1', 'LANG2', 'LANG3', 'LANG4', 'LANG5', 'LANG6', 'LANG7', 'LANG8', 'LANG9']

visual_pat_test = ['VISSPAT1','VISSPAT2', 'VISSPAT3', 'VISSPAT4', 'VISSPAT5', 'VISSPAT6', 'VISSPAT7', 'VISSPAT8']

planning_test = [ 'PLAN1' 'PLAN2', 'PLAN3', 'PLAN4', 'PLAN5']

organisation_test = ['ORGAN1', 'ORGAN2', 'ORGAN3', 'ORGAN4', 'ORGAN5', 'ORGAN6']

multi_task_test = ['DIVATT1', 'DIVATT2', 'DIVATT3', 'DIVATT4']

clock_test = ['CLOCKCIRC', 'CLOCKSYM', 'CLOCKNUM', 'CLOCKHAND', 'CLOCKTIME']

circle_test = ['COPYCIRC', 'COPYSYM', 'COPYNUM', 'COPYHAND', 'COPYTIME']

fluency_test = ['CATANIMSC','CATANPERS','CATANINTR','CATVEGESC','CATVGPERS', 'CATVGINTR']

mm_test = ['MMDATE', 'MMDATECM', 'MMYEAR', 'MMYEARCM', 'MMMONTH', 'MMMNTHCM', 'MMDAY', 'MMDAYCM', 'MMSEASON','MMSESNCM',
'MMHOSPIT','MMHOSPCM','MMFLOOR','MMFLRCM','MMCITY','MMCITYCM','MMAREA','MMAREACM','MMSTATE','MMSTCM','MMBALL',
'MMFLAG','MMTREE','MMTRIALS','MMD','MMDLTR','MML','MMLLTR','MMR','MMRLTR','MMO','MMOLTR','MMW','MMWLTR','MMBALLDL',
'MMFLAGDL','MMTREEDL','MMWATCH','MMPENCIL','MMREPEAT','MMHAND','MMFOLD','MMONFLR','MMREAD','MMWRITE','MMDRAW']

words_q_unable = ['Q2UNABLE', 'Q3UNABLE', 'Q4UNABLE', 'Q5UNABLE', 'Q6UNABLE', 'Q7UNABLE', 'Q8UNABLE', 'Q13UNABLE']

words_q1 = ['Q1TR1', 'Q1TR2', 'Q1TR3']
words_q2 = ['Q2TASK']
words_q3 = ['Q3TASK1', 'Q3TASK2', 'Q3TASK3', 'Q3TASK4']
words_q4 = ['Q4TASK']
words_q5 = ['Q5TASK']
words_q6 = ['Q6TASK']
words_q7 = ['Q7TASK']
words_q8 = ['Q8WORD1','Q8WORD1R','Q8WORD2','Q8WORD2R','Q8WORD3','Q8WORD3R','Q8WORD4','Q8WORD4R','Q8WORD5','Q8WORD5R','Q8WORD6','Q8WORD6R','Q8WORD7','Q8WORD7R','Q8WORD8','Q8WORD8R','Q8WORD9','Q8WORD9R','Q8WORD10',
'Q8WORD10R','Q8WORD11','Q8WORD11R','Q8WORD12','Q8WORD12R','Q8WORD13','Q8WORD13R','Q8WORD14','Q8WORD14R','Q8WORD15','Q8WORD15R','Q8WORD16','Q8WORD16R','Q8WORD17',
'Q8WORD17R','Q8WORD18','Q8WORD18R','Q8WORD19','Q8WORD19R','Q8WORD20','Q8WORD20R','Q8WORD21','Q8WORD21R','Q8WORD22','Q8WORD22R','Q8WORD23', 'Q8WORD23R','Q8WORD24','Q8WORD24R']
words_q9 = ['Q9TASK']
words_q10 = ['Q10TASK']
words_q11 = ['Q11TASK']
words_q12 = ['Q12TASK']
words_q13 = ['Q13TASKA', 'Q13TASKB', 'Q13TASKC']
